// <auto-generated />
using System;
using HospitalManagementSystemV3.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HospitalManagementSystemV3.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.6");

            modelBuilder.Entity("Appointment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("DoctorId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PatientId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DoctorId");

                    b.HasIndex("PatientId");

                    b.ToTable("Appointments");

                    b.HasData(
                        new
                        {
                            Id = new Guid("c00e7a77-123e-4b9f-b3dc-30d72d0f016a"),
                            Description = "General Checkup",
                            DoctorId = new Guid("7a4ad876-faa5-4f06-904b-434ac27e8c77"),
                            PatientId = new Guid("381b1fbb-27fd-490d-980f-ee915646dee2")
                        },
                        new
                        {
                            Id = new Guid("95fd3ea6-ed7c-4fbb-b3b6-7c25d7be0233"),
                            Description = "Follow-up Visit",
                            DoctorId = new Guid("7a4ad876-faa5-4f06-904b-434ac27e8c77"),
                            PatientId = new Guid("fb1d0e77-3ab1-4fe3-ab19-c37be23d4816")
                        },
                        new
                        {
                            Id = new Guid("2d270ba2-748b-45e6-bfe5-12c1e39b490e"),
                            Description = "Consultation",
                            DoctorId = new Guid("d4eb8113-9d41-4000-aee5-2c2282fe39a8"),
                            PatientId = new Guid("5b83a9fd-de61-4c10-a0d7-b79a861d23d3")
                        });
                });

            modelBuilder.Entity("Doctor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Doctors");

                    b.HasData(
                        new
                        {
                            Id = new Guid("7a4ad876-faa5-4f06-904b-434ac27e8c77"),
                            Address = "123 Main St, Anytown, USA",
                            Email = "john.doe@example.com",
                            Name = "Dr. John Doe",
                            Password = "password123",
                            Phone = "123-456-7890",
                            Username = "john_doe"
                        },
                        new
                        {
                            Id = new Guid("d4eb8113-9d41-4000-aee5-2c2282fe39a8"),
                            Address = "456 Oak St, Anytown, USA",
                            Email = "jane.smith@example.com",
                            Name = "Dr. Jane Smith",
                            Password = "password123",
                            Phone = "098-765-4321",
                            Username = "jane_smith"
                        });
                });

            modelBuilder.Entity("HospitalManagementSystemV3.Models.Admin", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Admins");
                });

            modelBuilder.Entity("HospitalManagementSystemV3.Models.Patient", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("DoctorId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DoctorId");

                    b.ToTable("Patients");

                    b.HasData(
                        new
                        {
                            Id = new Guid("381b1fbb-27fd-490d-980f-ee915646dee2"),
                            Address = "789 Pine St, Anytown, USA",
                            DoctorId = new Guid("7a4ad876-faa5-4f06-904b-434ac27e8c77"),
                            Email = "patient.one@example.com",
                            Name = "Patient One",
                            Password = "password123",
                            Phone = "111-222-3333",
                            Username = "patient_one"
                        },
                        new
                        {
                            Id = new Guid("fb1d0e77-3ab1-4fe3-ab19-c37be23d4816"),
                            Address = "321 Elm St, Anytown, USA",
                            DoctorId = new Guid("7a4ad876-faa5-4f06-904b-434ac27e8c77"),
                            Email = "patient.two@example.com",
                            Name = "Patient Two",
                            Password = "password123",
                            Phone = "444-555-6666",
                            Username = "patient_two"
                        },
                        new
                        {
                            Id = new Guid("5b83a9fd-de61-4c10-a0d7-b79a861d23d3"),
                            Address = "654 Birch St, Anytown, USA",
                            DoctorId = new Guid("d4eb8113-9d41-4000-aee5-2c2282fe39a8"),
                            Email = "patient.three@example.com",
                            Name = "Patient Three",
                            Password = "password123",
                            Phone = "777-888-9999",
                            Username = "patient_three"
                        });
                });

            modelBuilder.Entity("Appointment", b =>
                {
                    b.HasOne("Doctor", "Doctor")
                        .WithMany("Appointments")
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HospitalManagementSystemV3.Models.Patient", "Patient")
                        .WithMany("Appointments")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Doctor");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("HospitalManagementSystemV3.Models.Patient", b =>
                {
                    b.HasOne("Doctor", "Doctor")
                        .WithMany("Patients")
                        .HasForeignKey("DoctorId");

                    b.Navigation("Doctor");
                });

            modelBuilder.Entity("Doctor", b =>
                {
                    b.Navigation("Appointments");

                    b.Navigation("Patients");
                });

            modelBuilder.Entity("HospitalManagementSystemV3.Models.Patient", b =>
                {
                    b.Navigation("Appointments");
                });
#pragma warning restore 612, 618
        }
    }
}
